name: test-backend

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Spotless check (all services)
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "===> Spotless $dir"
              (cd "$dir" && mvn -B spotless:check) || exit 1
            fi
          done

      - name: Run unit tests (all services)
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "===> Test $dir"
              (cd "$dir" && mvn -B test) || exit 1
            fi
          done

      # For 1 repo 1 service
      - name: SonarCloud analysis (per service)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          for dir in admin-service ai-service api-gateway auth-service blog-service email-service interaction-service media-service notification-service payment-service user-service; do
            echo "Analyzing $dir"
            (
              cd $dir && mvn -B verify \
                org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar \
                -Dsonar.projectKey=My-Developer-Journey_${dir} \
                -Dsonar.organization=my-developer-journey \
                -Dsonar.projectName=${dir} \
                -Dsonar.host.url=https://sonarcloud.io
            ) || exit 1
          done
