name: test-backend

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Spotless check (all services)
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "===> Spotless $dir"
              (cd "$dir" && mvn -B spotless:check) || exit 1
            fi
          done

      - name: Run unit tests (all services)
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "===> Test $dir"
              (cd "$dir" && mvn -B test) || exit 1
            fi
          done

      - name: SonarCloud analysis (all services)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              SERVICE_NAME=$(basename "$dir")
              echo "===> Sonar analyze $SERVICE_NAME"

              (cd "$dir" && mvn -B verify sonar:sonar \
                -Dsonar.projectKey=diemyolo_$SERVICE_NAME \
                -Dsonar.organization=diemyolo \
                -Dsonar.projectName=$SERVICE_NAME \
              ) ||